version: "3.8"

services:
  frontend:
    build:
      context: ./frontend
      args:
        VITE_API_URL: http://api:8800 # internal Docker service URL
    ports:
      - "5173:5173"  # Vite default dev port
    depends_on:
      - api
    command: npm run dev -- --host  # run Vite dev server
    networks:
      - appnet

  api:
    build: ./API
    volumes:
      - ./API:/app
    depends_on:
      - db
    ports:
      - "8800:8800" 
    networks:
      - appnet

  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: social
    volumes:
      - ./mydevify_social.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - appnet

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - "8080:80"
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: root
    networks:
      - appnet

networks:
  appnet:
    driver: bridge
