version: "3.8"

services:
  frontend:
    build:
      context: ./frontend
    environment: #should be at same level of build 
      VITE_API_URL: http://api:8800 # internal Docker service URL
    ports:
      - "5173:5173"  # Vite default dev port
    depends_on:
      - api
    networks:
      - appnet

  api:
    build: ./API  ##Use the expanded form (build: { context: ..., dockerfile: ..., args: ... }) if you need to specify additional build options, such as a custom Dockerfile name or build arguments.
    # Volume removed because we dont want live reload .. and we are going to push this on production 
    depends_on:
      - db
    networks:
      - appnet

  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: social
    volumes:
      - ./mydevify_social.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - appnet
    #healthcheck:
    #  test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-proot"]
    #  interval: 10s
    #  timeout: 20s
    #  retries: 50
    #  start_period: 30s
    ## check how we can add health check for my sql db cointairner in docker compose file s

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - "8080:80"
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: root
    networks:
      - appnet

networks:
  appnet:
    driver: bridge
