version: "3.8"

services:
  frontend:
    build:
      context: ./frontend
      args:
        VITE_API_URL: http://api:8800  #https://your-domain.com/api  or if using internal networking
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - api

  api:
    build: ./API
    ports:
      - "8800:8800"
    volumes:
      - ./API:/app
    depends_on:
      - db

  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: social
    volumes:
      - ./mydevify_social.sql:/docker-entrypoint-initdb.d/init.sql


  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - "8080:80"
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: root

volumes:
  db_data:
